version: "3.9"

services:
  back:
    build: ./back
    container_name: vtb-api-back
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./vtb_api.db
    volumes:
      - ./back:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
