version: "3.9"

services:
  back:
    build: ./back
    container_name: vtb-api-back
    ports:
      - "8000:8000"
    environment:
      DB_URL: sqlite+aiosqlite:///./vtb_api.db
    volumes:
      - ./back:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: vtb-api-front
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
      - CI=true
    volumes:
      - ./front:/app
      - /app/node_modules
    command: sh -c "pnpm install --frozen-lockfile && pnpm run dev --host"
